# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Martin Jedwabny
tagline:          'PhD. student at the University of Montpellier'
description:      'PhD. student at the University of Montpellier'
url:              https://martinjedwabny.github.io
baseurl:          /

author:
  name:           'Martin Jedwabny'
  url:            https://martinjedwabny.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll/scholar

paginate:         5

excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/martinjedwabny

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
